version: 3.8

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: multistage-food
  # no port because only reached via nginx
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    depends_on:
      - web
    ports:
      - "80:80"
